[package]
name = "rust-focus"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
serde = {version = "1", features=["derive"]}
clap = {version = "4.5", features = ["derive"]}